# This file stores configurations for your Shopify app.

scopes = "write_products,write_customers,write_discounts,write_price_rules,read_product_listings,write_orders,write_draft_orders,write_checkouts"
