# This file stores configurations for your Shopify app.

# price_rules

scopes = "read_fulfillments,write_customers,write_discounts,write_price_rules,read_customers,orders,read_orders,write_orders,read_products"
